version: '3.9'

services:
  laravel-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: laravel-inertia-app
    container_name: laravel-inertia-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
      - ./docker/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/apache-config.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - laravelnet
    ports:
      - "9000:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - DB_CONNECTION=mysql
      - DB_HOST=prod-laravel-inertia.c3cg8e88ygqb.eu-north-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=DB_DATABASE=tasksystem
      - DB_USERNAME=prod_laravel_in
      - DB_PASSWORD=>:W8r.I$fVPD.s8|ZE1WFT1P>kg6

  nginx:
    image: nginx:alpine
    container_name: laravel-inertia-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./laravel-app:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - laravelnet

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=prod-laravel-inertia.c3cg8e88ygqb.eu-north-1.rds.amazonaws.com
      - MYSQL_ROOT_PASSWORD=>:W8r.I$fVPD.s8|ZE1WFT1P>kg6
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge
